Bitirme_Projem_MVC/Controllers/KelimeListemController.cs
using Bitirme_Projem_BussinesLayer;
using Bitirme_Projem_Entities;
using Bitirme_Projem_Entities.ValueObject;
using Bitirme_Projem_MVC.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bitirme_Projem_MVC.Controllers
{
    public class KelimeListemController : Controller
    {
        // GET: KelimeListem 
        KullaniciListeManager liste = new KullaniciListeManager();
        Kullanıcı_Kelime_Manager manager = new Kullanıcı_Kelime_Manager();
        GuncelleManager guncelle = new GuncelleManager();
        AdminManager admin = new AdminManager();
        [Auth]
        public ActionResult KelimeListesi()
        {
            return View();
        }
       
        [HttpPost]
        public JsonResult Kelimelistesi(int id, int Kategoriid)
        {
            List<Kelimeler> Kelime = liste.KelimeListesi();
            List<Kullanıcı_Kelime> KullaniciKelime = liste.KullaniciKelimeListesi();
            var Kelimeler = (from x in Kelime
                             join k in KullaniciKelime on x.Kelime_Id equals k.Kelime_Id
                             where k.Kullanicı_Id == id && k.Kategori_Id == Kategoriid
                             select new
                             {
                                 Kelimeid = x.Kelime_Id,
                                 Kelime = x.Kelime_İng,
                                 Anlami = x.Kelime_Turk,
                                 Tekrarsayisi = x.Tekrarsayıs
                             }

                           ).ToList();

            return Json(Kelimeler, JsonRequestBehavior.AllowGet);
        }
      
        [HttpPost]
        public JsonResult OgrenecegimGuncelle(int Kullaniciid, int Kategoriid, int Kelimeid)
        {
          int sonuc=  guncelle.OgrenecegimKelimeGuncelle(Kullaniciid, Kelimeid, Kategoriid);
            if (sonuc > 0)
            {
                return Json(new { result = true },JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { result = false }, JsonRequestBehavior.AllowGet);
            }

        }
      
        [HttpPost]
        public JsonResult BildigimGuncelle(int Kullaniciid, int Kategoriid, int Kelimeid)
        {
            int sonuc = guncelle.BildigimKelimeGuncelle(Kullaniciid, Kelimeid, Kategoriid);
            if (sonuc > 0)
            {
                return Json(new { result = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { result = false }, JsonRequestBehavior.AllowGet);
            }

        }

        [Auth]
        public ActionResult ÖğrenceğimKelime()
        {
            return View();
        }
        [Auth]
        public ActionResult BildiğimKelime()
        {
            return View();
        }
        [HttpGet]
        public ActionResult KelimeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult KelimeEkle(Kelimeler model)
        {
         
            var id = Session["user_id"];
            admin.KelimeEkleme(model.Kelime_İng, model.Kelime_Turk, model.Tekrarsayıs);

            Kelimeler Kelimem = admin.KelimeListe(model.Kelime_İng, model.Kelime_Turk);
               
            
            int deger=manager.KelimeListemeEkle(Convert.ToInt32(id), 1,Kelimem.Kelime_Id );
            
            return View(model);
        }
    }
}

Bitirme_Projem_MVC/Views/KelimeListem/BildiğimKelime.cshtml
@{
    ViewBag.Title = "BildiğimKelime";
    Layout = "~/Views/Shared/AnaEkran.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
    <input type="hidden" id="session" value=@Session["user_id"] />
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2> <b id="tikla">Kelime Listem</b></h2>
                        </div>

                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>


                            <th>No</th>
                            <th>Kelime</th>
                            <th>Anlamı</th>
                            <th>Tekrar Sayısı</th>
                            <th>Aksiyon</th>
                        </tr>
                    </thead>
                    <tbody id="TableBody"></tbody>
                </table>

            </div>
        </div>
    </div>


</body>
</html>
@section scripts{
   



    <script type="text/javascript">
        function Bildigimler() {
            var kategori = 2;
            var x = document.getElementById("session").value;



            $.ajax({
                url: '/KelimeListem/Kelimelistesi',
                type: 'POST',
                dataType: 'json',

                data: { id: x, Kategoriid: kategori },

                success: function (data) {

                    $.each(data, function (index, deger) {
                        index++;
                        var deger = "<tr ><td>" + index + "</td><td >" + deger.Kelime + "</td><td>" + deger.Anlami + "</td><td>" + deger.Tekrarsayisi + "</td><td class='d-flex justify-content-around'><a href='#editEmployeeModal' onClick = 'Ogrenecekler(" + deger.Kelimeid + "," + document.getElementById("session").value + ");'   class='edit d-inline-block' data-toggle='modal'><i  class='fas fa-fw fa-chart-area' data-toggle='tooltip' title='Öğreneceğim Kelime'>&#xE254;</i></a></td></tr>";
                        $('#TableBody').append(deger);





                    });



                }


            });
        }
        $(document).ready(function () {

            Bildigimler();


        });

    </script>

    <script src="~/js/Action5.js"></script>

}

Bitirme_Projem_MVC/Views/KelimeListem/KelimeEkle.cshtml
@model Bitirme_Projem_Entities.Kelimeler
@{
    ViewBag.Title = "KelimeEkle";
    Layout = "~/Views/Shared/AnaEkran.cshtml";
}
@{

}

<span style="color:red">@Html.ValidationSummary()</span>
@using (Html.BeginForm("KelimeEkle", "KelimeListem", FormMethod.Post))
{

    
    <div class="form-group ml-3">
        <label for="exampleInputEmail1">Kelime</label>
        @Html.TextBoxFor(x => x.Kelime_İng, new { @class = "form-control", placeholder = "Kelimeyi Giriniz" })


    </div>
    <div class="form-group ml-3">
        <label for="exampleInputPassword1">Kelime Anlamı</label>
        @Html.TextBoxFor(x => x.Kelime_Turk, new { @class = "form-control", placeholder = "Kelimeyi Anlamını Giriniz" })
    </div>

    <button type="submit" onclick="sayi(@Session["user_id"])" class="btn btn-primary ml-3">Kelime Listeme Ekle</button>
}

  

Bitirme_Projem_MVC/Views/KelimeListem/KelimeListesi.cshtml
@{
    ViewBag.Title = "KelimeListesi";
    Layout = "~/Views/Shared/AnaEkran.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
    <input type="hidden" id="session" value=@Session["user_id"] />
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2> <b id="tikla">Kelime Listem</b></h2>
                        </div>

                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>


                            <th>No</th>
                            <th>Kelime</th>
                            <th>Anlamı</th>
                            <th>Tekrar Sayısı</th>
                            <th>Aksiyon</th>
                        </tr>
                    </thead>
                    <tbody id="TableBody"></tbody>
                </table>

            </div>
        </div>
    </div>


</body>
</html>
@section scripts{




    <script type="text/javascript">

        function KelimeListesii() {
            var kategori = 1;
            var x = document.getElementById("session").value;



            $.ajax({
                url: '/KelimeListem/Kelimelistesi',
                type: 'POST',
                dataType: 'json',

                data: { id: x, Kategoriid: kategori },

                success: function (data) {

                    $.each(data, function (index, deger) {
                        index++;
                        var deger = "<tr ><td>" + index + "</td><td >" + deger.Kelime + "</td><td>" + deger.Anlami + "</td><td>" + deger.Tekrarsayisi + "</td><td class='d-flex justify-content-around'><a href='#editEmployeeModal' onClick = 'Bildigimogrenecegim(" + deger.Kelimeid + "," + document.getElementById("session").value + ");'   class='edit d-inline-block' data-toggle='modal'><i  class='fas fa-fw fa-chart-area' data-toggle='tooltip' title='Öğreneceğim Kelime'>&#xE254;</i></a>  <a href='#deleteEmployeeModal' onClick = 'BildigimListe(" + deger.Kelimeid + "," + document.getElementById("session").value + ");' class='delete ' data-toggle='modal'><i class='fas fa-check fa-2x'style='color: #66ff00' data-toggle='tooltip' title='Bildiğim Kelime'></i></a></td></tr>";
                        $('#TableBody').append(deger);





                    });



                }


            });

        }
        $(document).ready(function () {

            KelimeListesii();

        });

    </script>

    <script src="~/js/Action6.js"></script>
    
}

Bitirme_Projem_MVC/Views/KelimeListem/ÖğrenceğimKelime.cshtml
@{
    ViewBag.Title = "ÖğrenceğimKelime";
    Layout = "~/Views/Shared/AnaEkran.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

</head>
<body>
    <input type="hidden" id="session" value=@Session["user_id"] />
    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-12">
                            <h2> <b id="tikla">Ögrenecegim Kelimeler</b></h2>
                        </div>

                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>


                            <th>No</th>
                            <th>Kelime</th>
                            <th>Anlamı</th>
                            <th>Tekrar Sayısı</th>
                            <th>Aksiyon</th>
                        </tr>
                    </thead>
                    <tbody id="TableBody"></tbody>
                </table>

            </div>
        </div>
    </div>


</body>
</html>
@section scripts{




    <script type="text/javascript">
       
        function Ogrenecegimiii() {
            var kategori = 3;
            var x = document.getElementById("session").value;



            $.ajax({
                url: '/KelimeListem/Kelimelistesi',
                type: 'POST',
                dataType: 'json',

                data: { id: x, Kategoriid: kategori },

                success: function (data) {

                    $.each(data, function (index, deger) {
                        index++;
                        var deger = "<tr ><td>" + index + "</td><td >" + deger.Kelime + "</td><td>" + deger.Anlami + "</td><td>" + deger.Tekrarsayisi + "</td><td class='d-flex justify-content-around'> <a href='#deleteEmployeeModal' onClick = 'BildigimKelimeler(" + deger.Kelimeid + "," + document.getElementById("session").value + ");' class='delete ' data-toggle='modal'><i class='fas fa-check fa-2x'style='color: #66ff00' data-toggle='tooltip' title='Bildiğim Kelime'></i></a></td></tr>";
                        $('#TableBody').append(deger);


                        

                    });



                }


            });

        }

        $(document).ready(function () {
            Ogrenecegimiii();
            });
        
    </script>

    <script src="~/js/Action4.js"></script>

}